name: Deploy next.js app to docker hub

on:
  push:
    branches: 
      - main

jobs:
  build_and_deploy_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Login to Docker Hub
         uses: docker/login-action@v2
