name: Deploy next.js app to docker hub

on:
  push:
    branches: 
      - main
      

jobs:
  build_and_deploy_to_docker_hub:
    runs-on: ubuntu-latest

    env:
          DISABLE_ESLINT: true

    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and push Docker image
         uses: docker/build-push-action@v4
         with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
