name: Deploy next.js app to docker hub

on:
  push:
    branches: 
      - main
      

jobs:
  build_and_deploy_to_docker_hub:
    runs-on: ubuntu-latest

    env:
          DISABLE_ESLINT: true

    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and push Docker image
         uses: docker/build-push-action@v4
         with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
            VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}
            VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}
            VAPID_EMAIL=${{ secrets.VAPID_EMAIL }}
            NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy_to_docker_hub
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker system prune -af --volumes
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }}
            sudo docker stop nextjs-app || true
            sudo docker rm nextjs-app || true
            sudo docker run -d --name nextjs-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/nextjs-app:${{ github.sha }}